// Generated by jtd-codegen (https://github.com/simbo1905/jtd-wasm)
// This code is generated from a JSON Type Definition schema.
// Do not edit manually.

#![allow(unused_variables, clippy::unnecessary_map_or, clippy::useless_format, clippy::collapsible_if)]

use serde_json::Value;

fn validate_interesting_event(v: &Value, e: &mut Vec<(String, String)>, p: &str, sp: &str) {
  if let Some(obj) = v.as_object() {
    if let Some(pv) = obj.get("event_type") {
      let ip_p_event_type = format!("{p}/event_type");
      let sp_p_event_type = format!("{sp}/properties/event_type");
      if !pv.is_string() {
        e.push((ip_p_event_type.to_string(), format!("{sp_p_event_type}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/event_type")));
    }
    if let Some(pv) = obj.get("gap_lines") {
      let ip_p_gap_lines = format!("{p}/gap_lines");
      let sp_p_gap_lines = format!("{sp}/properties/gap_lines");
      if !pv.as_f64().map_or(false, |n| n.is_finite()) {
        e.push((ip_p_gap_lines.to_string(), format!("{sp_p_gap_lines}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/gap_lines")));
    }
    if let Some(pv) = obj.get("line_number") {
      let ip_p_line_number = format!("{p}/line_number");
      let sp_p_line_number = format!("{sp}/properties/line_number");
      if !pv.as_f64().map_or(false, |n| n.is_finite()) {
        e.push((ip_p_line_number.to_string(), format!("{sp_p_line_number}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/line_number")));
    }
    if let Some(pv) = obj.get("summary") {
      let ip_p_summary = format!("{p}/summary");
      let sp_p_summary = format!("{sp}/properties/summary");
      if !pv.is_string() {
        e.push((ip_p_summary.to_string(), format!("{sp_p_summary}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/summary")));
    }
    for k in obj.keys() {
      if k.as_str() != "event_type" && k.as_str() != "gap_lines" && k.as_str() != "line_number" && k.as_str() != "summary" {
        e.push((format!("{p}/{k}"), sp.to_string()));
      }
    }
  } else {
    e.push((p.to_string(), format!("{sp}/properties")));
  }
}

fn validate_profile(v: &Value, e: &mut Vec<(String, String)>, p: &str, sp: &str) {
  if let Some(obj) = v.as_object() {
    if let Some(pv) = obj.get("file_size") {
      let ip_p_file_size = format!("{p}/file_size");
      let sp_p_file_size = format!("{sp}/properties/file_size");
      if !pv.as_f64().map_or(false, |n| n.is_finite()) {
        e.push((ip_p_file_size.to_string(), format!("{sp_p_file_size}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/file_size")));
    }
    if let Some(pv) = obj.get("first_ts") {
      let ip_p_first_ts = format!("{p}/first_ts");
      let sp_p_first_ts = format!("{sp}/properties/first_ts");
      if !pv.is_null() {
        if !pv.is_string() {
          e.push((ip_p_first_ts.to_string(), format!("{sp_p_first_ts}/type")));
        }
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/first_ts")));
    }
    if let Some(pv) = obj.get("has_tantivy_index") {
      let ip_p_has_tantivy_index = format!("{p}/has_tantivy_index");
      let sp_p_has_tantivy_index = format!("{sp}/properties/has_tantivy_index");
      if !pv.is_boolean() {
        e.push((ip_p_has_tantivy_index.to_string(), format!("{sp_p_has_tantivy_index}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/has_tantivy_index")));
    }
    if let Some(pv) = obj.get("interesting_events") {
      let ip_p_interesting_events = format!("{p}/interesting_events");
      let sp_p_interesting_events = format!("{sp}/properties/interesting_events");
      if let Some(arr) = pv.as_array() {
        for (i, elem) in arr.iter().enumerate() {
          let ip_e0 = format!("{ip_p_interesting_events}/{i}");
          let sp_e0 = format!("{sp_p_interesting_events}/elements");
          validate_interesting_event(elem, e, &ip_e0, &format!("/definitions/interesting_event"));
        }
      } else {
        e.push((ip_p_interesting_events.to_string(), format!("{sp_p_interesting_events}/elements")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/interesting_events")));
    }
    if let Some(pv) = obj.get("last_ts") {
      let ip_p_last_ts = format!("{p}/last_ts");
      let sp_p_last_ts = format!("{sp}/properties/last_ts");
      if !pv.is_null() {
        if !pv.is_string() {
          e.push((ip_p_last_ts.to_string(), format!("{sp_p_last_ts}/type")));
        }
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/last_ts")));
    }
    if let Some(pv) = obj.get("line_count") {
      let ip_p_line_count = format!("{p}/line_count");
      let sp_p_line_count = format!("{sp}/properties/line_count");
      if !pv.as_f64().map_or(false, |n| n.is_finite()) {
        e.push((ip_p_line_count.to_string(), format!("{sp_p_line_count}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/line_count")));
    }
    if let Some(pv) = obj.get("role_counts") {
      let ip_p_role_counts = format!("{p}/role_counts");
      let sp_p_role_counts = format!("{sp}/properties/role_counts");
      if let Some(obj) = pv.as_object() {
        for (k, vv) in obj {
          let ip_v0 = format!("{ip_p_role_counts}/{k}");
          let sp_v0 = format!("{sp_p_role_counts}/values");
          if !vv.as_f64().map_or(false, |n| n.is_finite()) {
            e.push((ip_v0.to_string(), format!("{sp_v0}/type")));
          }
        }
      } else {
        e.push((ip_p_role_counts.to_string(), format!("{sp_p_role_counts}/values")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/role_counts")));
    }
    if let Some(pv) = obj.get("session_id") {
      let ip_p_session_id = format!("{p}/session_id");
      let sp_p_session_id = format!("{sp}/properties/session_id");
      if !pv.is_string() {
        e.push((ip_p_session_id.to_string(), format!("{sp_p_session_id}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/session_id")));
    }
    for k in obj.keys() {
      if k.as_str() != "file_size" && k.as_str() != "first_ts" && k.as_str() != "has_tantivy_index" && k.as_str() != "interesting_events" && k.as_str() != "last_ts" && k.as_str() != "line_count" && k.as_str() != "role_counts" && k.as_str() != "session_id" {
        e.push((format!("{p}/{k}"), sp.to_string()));
      }
    }
  } else {
    e.push((p.to_string(), format!("{sp}/properties")));
  }
}

pub fn validate(instance: &Value) -> Vec<(String, String)> {
  let mut e: Vec<(String, String)> = Vec::new();
  let p = "";
  let sp = "";
  if let Some(obj) = instance.as_object() {
    if let Some(pv) = obj.get("profile") {
      let ip_p_profile = format!("{p}/profile");
      let sp_p_profile = format!("{sp}/properties/profile");
      validate_profile(pv, &mut e, &ip_p_profile, &format!("/definitions/profile"));
    } else {
      e.push((p.to_string(), format!("{sp}/properties/profile")));
    }
    if let Some(pv) = obj.get("session_id") {
      let ip_p_session_id = format!("{p}/session_id");
      let sp_p_session_id = format!("{sp}/properties/session_id");
      if !pv.is_string() {
        e.push((ip_p_session_id.to_string(), format!("{sp_p_session_id}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/session_id")));
    }
    if let Some(pv) = obj.get("written_at_epoch_ms") {
      let ip_p_written_at_epoch_ms = format!("{p}/written_at_epoch_ms");
      let sp_p_written_at_epoch_ms = format!("{sp}/properties/written_at_epoch_ms");
      if !pv.as_f64().map_or(false, |n| n.is_finite()) {
        e.push((ip_p_written_at_epoch_ms.to_string(), format!("{sp_p_written_at_epoch_ms}/type")));
      }
    } else {
      e.push((p.to_string(), format!("{sp}/properties/written_at_epoch_ms")));
    }
    for k in obj.keys() {
      if k.as_str() != "profile" && k.as_str() != "session_id" && k.as_str() != "written_at_epoch_ms" {
        e.push((format!("{p}/{k}"), sp.to_string()));
      }
    }
  } else {
    e.push((p.to_string(), format!("{sp}/properties")));
  }
  e
}

// --- Adaptation: typed envelope + conversion into the real SessionProfile ---
// The generated validator above is the JTD gate; these types deserialize the
// validated JSON and convert into crate::rollout::SessionProfile. EventType
// is stored as its variant name (matching serde serialization) and is
// validated back into the enum here — an unknown name fails the conversion,
// which the caller treats as a corrupt cache.

use std::collections::HashMap;

use crate::rollout::{EventType, InterestingEvent, SessionProfile};

#[derive(Debug, Clone, serde::Deserialize)]
pub struct ProfileCacheEnvelope {
    pub session_id: String,
    pub written_at_epoch_ms: u64,
    pub profile: CachedProfile,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct CachedProfile {
    pub session_id: String,
    pub file_size: u64,
    pub line_count: u64,
    pub first_ts: Option<String>,
    pub last_ts: Option<String>,
    pub role_counts: HashMap<String, u64>,
    pub has_tantivy_index: bool,
    pub interesting_events: Vec<CachedInterestingEvent>,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct CachedInterestingEvent {
    pub line_number: u64,
    pub event_type: String,
    pub summary: String,
    pub gap_lines: u64,
}

fn event_type_from_name(name: &str) -> Option<EventType> {
    match name {
        "Compaction" => Some(EventType::Compaction),
        "TodoCreate" => Some(EventType::TodoCreate),
        "TodoUpdate" => Some(EventType::TodoUpdate),
        "TodoDelete" => Some(EventType::TodoDelete),
        "GitCommit" => Some(EventType::GitCommit),
        "GitPush" => Some(EventType::GitPush),
        "GitTag" => Some(EventType::GitTag),
        "UserMessage" => Some(EventType::UserMessage),
        _ => None,
    }
}

impl TryFrom<ProfileCacheEnvelope> for SessionProfile {
    type Error = ();

    fn try_from(envelope: ProfileCacheEnvelope) -> Result<Self, Self::Error> {
        let mut interesting_events =
            Vec::with_capacity(envelope.profile.interesting_events.len());
        for event in envelope.profile.interesting_events {
            interesting_events.push(InterestingEvent {
                line_number: event.line_number,
                event_type: event_type_from_name(&event.event_type).ok_or(())?,
                summary: event.summary,
                gap_lines: event.gap_lines,
            });
        }
        Ok(SessionProfile {
            session_id: envelope.profile.session_id,
            file_size: envelope.profile.file_size,
            line_count: envelope.profile.line_count,
            first_ts: envelope.profile.first_ts,
            last_ts: envelope.profile.last_ts,
            role_counts: envelope.profile.role_counts,
            has_tantivy_index: envelope.profile.has_tantivy_index,
            interesting_events,
        })
    }
}

/// Build the cache envelope from a profile. The profile is serialized through
/// its own serde impl so the cached bytes match `SessionProfile` serialization
/// exactly; only `event_type` (an enum) is pre-flattened by that impl.
pub fn envelope_json(profile: &SessionProfile, written_at_epoch_ms: u64) -> Value {
    Value::Object({
        let mut map = serde_json::Map::new();
        map.insert("session_id".into(), Value::String(profile.session_id.clone()));
        map.insert(
            "written_at_epoch_ms".into(),
            Value::from(written_at_epoch_ms),
        );
        map.insert(
            "profile".into(),
            serde_json::to_value(profile).unwrap_or(Value::Null),
        );
        map
    })
}
